// @ts-nocheck

import TopBanner from "./Components/TopBanner";
import BottomNav from "./Components/BottomNav";

export const metadata = {
  title: "DEV",
  description: "Generated by create next app",
};
import "../styles/_global.scss";
import Footer from "./Components/Footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopBanner />
        <div>
          {children}

          <Footer />
        </div>
        <BottomNav />
      </body>
    </html>
  );
}
