// @ts-nocheck
import Image from "next/image";
import { Inter } from "next/font/google";

import "../styles/pages/home.scss";

// export const metadata = {
//   title: "스마트한 캐시백 습관-메인인인인",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main className="main-content">
      <h2>main</h2>
    </main>
  );
}
